name: "AWS Route 53 Geolocation Remover"
description: "This GitHub Action removes the geolocation records of a domain in AWS Route 53."
branding:
  color: 'green'
  icon: 'check-square'

runs:
  using: node16
  main: index.js
